let quotes = [
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe you can and you're halfway there.",
    "The best way to predict the future is to create it.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "It always seems impossible until it's done.",
    "Start where you are. Use what you have. Do what you can.",
    "Don't watch the clock; do what it does. Keep going.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Opportunities don't happen. You create them.",
    "Don't be afraid to give up the good to go for the great.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "Try not to become a man of success, but rather become a man of value.",
    "The road to success and the road to failure are almost exactly the same.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Courage is resistance to fear, mastery of fear—not absence of fear.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "I attribute my success to this: I never gave or took any excuse.",
    "Don't let yesterday take up too much of today.",
    "You learn more from failure than from success. Don't let it stop you.",
    "Failure will never overtake me if my determination to succeed is strong enough.",
    "People who are crazy enough to think they can change the world are the ones who do.",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do.",
    "We generate fears while we sit. We overcome them by action.",
    "The only way to do great work is to love what you do.",
    "Failure is another stepping stone to greatness.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Stay positive, work hard, make it happen.",
    "Your only limit is your mind.",
    "Act as if what you do makes a difference. It does.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Success is not about perfection; it's about progress.",
    "You don't have to be great to start, but you have to start to be great.",
    "Go the extra mile. It's never crowded there.",
    "The way to get started is to quit talking and begin doing.",
    "Be the change that you wish to see in the world.",
    "It's not whether you get knocked down; it's whether you get up.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "You don't need to see the whole staircase, just take the first step.",
    "Don't count the days, make the days count.",
    "Focus on being productive instead of busy.",
    "Work until your idols become your rivals.",
    "If you want to achieve greatness stop asking for permission.",
    "Great things take time. Be patient.",
    "Success is what happens after you have survived all of your mistakes.",
    "Hard times don't create heroes. It is during the hard times when the 'hero' within us is revealed.",
    "Your life only gets better when you get better.",
    "Success is not how far you got, but the distance you traveled from where you started.",
    "Success isn't about being the best. It's about always getting better.",
    "Success isn't overnight. It's when every day you get a little better than the day before. It all adds up.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Don't stop when you're tired; stop when you're done.",
    "The difference between who you are and who you want to be is what you do.",
    "The only place where success comes before work is in the dictionary.",
    "You don't have to be perfect to be amazing.",
    "Your attitude, not your aptitude, will determine your altitude.",
    "If you want to fly, you have to give up the things that weigh you down.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, so don't waste it living someone else's life.",
    "It always seems impossible until it's done.",
    "The only person you are destined to become is the person you decide to be.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
    "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
    "Success is a journey, not a destination.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Do not be embarrassed by your failures, learn from them and start again.",
    "Every strike brings me closer to the next home run.",
    "I never dreamed about success, I worked for it.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
];
const moreQuotes = [
    "The harder the conflict, the greater the triumph.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't wish it were easier. Wish you were better.",
    "What we achieve inwardly will change outer reality.",
    "A champion is defined not by their wins but by how they can recover when they fall.",
    "Great works are performed not by strength but by perseverance.",
    "Success is the sum of small efforts repeated day in and day out.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "If you fell down yesterday, stand up today.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "The only person you are destined to become is the person you decide to be.",
    "In the middle of difficulty lies opportunity.",
    "It's not about having time. It's about making time.",
    "If you can dream it, you can do it.",
    "The struggle you're in today is developing the strength you need for tomorrow.",
    "No masterpiece was ever created by a lazy artist.",
    "Hustle beats talent when talent doesn't hustle.",
    "You can either experience the pain of discipline or the pain of regret. The choice is yours.",
    "The way to get started is to quit talking and begin doing.",
    "You don't find willpower, you create it.",
    "Believe deep down in your heart that you're destined to do great things.",
    "Don't limit your challenges, challenge your limits.",
    "The only time you fail is when you fall down and stay down.",
    "Set your goals high, and don't stop till you get there.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Work hard in silence, let your success be your noise.",
    "Strive for progress, not perfection.",
    "Success isn't just about what you accomplish in your life; it's about what you inspire others to do.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Don't wait for the right moment. Create it.",
    "Do what you can, with what you have, where you are.",
    "Stay positive, work hard, and make it happen.",
    "You are capable of more than you know.",
    "Doubt kills more dreams than failure ever will.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "The secret of getting ahead is getting started.",
    "Dream big and dare to fail.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "Success is a state of mind. If you want success, start thinking of yourself as a success.",
    "Everything you've ever wanted is on the other side of fear.",
    "Start where you are, use what you have, do what you can.",
    "Don't be afraid to give up the good to go for the great.",
    "All our dreams can come true, if we have the courage to pursue them.",
    "Success doesn't come to you, you go to it.",
    "If it doesn't challenge you, it won't change you.",
    "You miss 100% of the shots you don't take.",
    "Act as if what you do makes a difference. It does.",
    "There is no substitute for hard work.",
    "The distance between insanity and genius is measured only by success.",
    "There is no elevator to success. You have to take the stairs.",
    "It's not the load that breaks you down, it's the way you carry it.",
    "Fall seven times, stand up eight.",
    "If you can imagine it, you can achieve it; if you can dream it, you can become it.",
    "Success is going from failure to failure without losing your enthusiasm.",
    "Great things never come from comfort zones.",
    "Nothing worth having comes easy.",
    "Success is not in what you have, but who you are.",
    "You are braver than you believe, stronger than you seem, and smarter than you think.",
    "The best revenge is massive success.",
    "Do what you love, and the money will follow.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "Dreams don't work unless you do.",
    "Perseverance is not a long race; it's many short races one after the other.",
    "Winners never quit, and quitters never win.",
    "Success is what happens when preparation meets opportunity.",
    "The secret to success is to know something nobody else knows.",
    "Opportunities don't happen. You create them.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success is liking yourself, liking what you do, and liking how you do it.",
    "It's not how good you are, it's how good you want to be.",
    "It's never too late to be what you might have been.",
    "Believe you can and you're halfway there.",
    "You may have to fight a battle more than once to win it.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Don't stop when you're tired, stop when you're done.",
    "Success is how high you bounce when you hit bottom.",
    "Action is the foundational key to all success.",
    "All progress takes place outside the comfort zone.",
    "Don't count the days, make the days count.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Don't wish for it, work for it.",
    "The harder you work, the luckier you get.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The question isn't who is going to let me; it's who is going to stop me.",
    "In the end, we only regret the chances we didn't take.",
    "There is no such thing as failure. Failure is just life trying to move us in another direction.",
    "The biggest risk is not taking any risk.",
    "Success doesn't happen to you, it happens because of you.",
    "Focus on the journey, not the destination.",
];

quotes = [...quotes, ...moreQuotes];

function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText = quotes[randomIndex];
}

// Generate a quote when the page loads
window.onload = generateQuote;
